README.md
I noticed only the Table of Contents was alphabetically arranged, so I re-arranged the contents as well to make navigation easier.
=> arrange content alphabetically

README.md
Added a section for machine learning
=> Added a section for machine learning

CONTRIBUTING.md, README.md
1. updated contributing guide into a list and clarified the alphabetical order requirement. 
2. Added 2 podcasts, women in tech section and 1 css. 
3. Updated table of contents name, organized it into alphabetical order and added the women in tech topic
=> Added resources and Fixed typos

README.md
Machine Learning Course by Andrew Ng Created by Standford University on Coursera
=> Added ML Resource

README.md
free pdf with R coding labs, datasets, and figures.
=> issue #10 Contributing machine learning in README.md

README.md
I added some resources on GraphQL
=> Add GraphQL resources

README.md
- Included Oracle Application Express (APEX)
- Added several links for useful resources for APEX Development.
=> Added Oracle APEX Useful Links

README.md
Hi,
I've added a few links on InfoSec Learnings. Because everything is better when it's secure. 
I'm not sure, if the courses on Reverse Engineering are actually _that_ useful for webdev - but i think they are just too good to skip ;)
=> Added InfoSec Resources

README.md
- Added resources for Oracle's PL/SQL
- Renamed Oracle APEX to better fit alphabetical order.
- Fixed some markdown issues.
=> Added PL/SQL + Fixed Markdown

README.md
Changes proposed in this pull request.
- Add DHH to developer blog.
- Reorder by name.
- Fix typo.
=> Add DHH to developer blog :bear:

README.md
Added some useful Angular Resources, per request in #38
=> Add Angular resources

README.md
Add Classy Class-Based Views in Django resources
Add Agile section + first resources
=> Django resources + Agile section

README.md
Frontend Masters has lots of amazing courses from experienced developers, I have added the react path for the same.
=> added frontend masters learning path for react

README.md
this pull request includes two guides from github.com one for visual learners and a regular guide, a playlist from freecodecamp youtube page explaining the fundamentals of git and github and a premium course from scotch.io on git and github
=> added resources for git and github

README.md
added new advanced react course from @wesbos in reactjs learning resources.
=> Fullstack Advanced React and GraphQL by Wes Bos

README.md
=> Fixing link for Indie Hackers podcast.

README.md
Added Masters of scale, Laracast snippet, Developer tea, and shop talk show to the podcast list.
=> Adding 4 new episodes to the podcast list

README.md
for issue #53 
change http links to https in all but 3 instances
these 3 sites had issue using to https:
https://www.fullstackradio.com/
https://podcast.womenintechshow.com/episodes
https://www.flatuicolorpicker.com/
so I left them as http://
=> change http to https

README.md
Hi,
I though this new category and a resource might be a good contribution to the list.
Thanks for considering it!
Branko
=> Added new category and Hugo in Action book

README.md
added Intro to Deep Learning with PyTorch course in Machine learning
=> added Intro to Deep Learning with PyTorch course

README.md
Added tutorials about creating skills for Alexa and actions for Google Assistant
=> Added Voice (Alexa/Google Assistant) Resources

README.md
added a new resource 'Angular in depth' to the Angular section
=> Update README.md, new resoruce for Angular

README.md
added bootstrap section and some resources
=> Added Bootstrap section

README.md
Added Twilio API Resources and fixed the spacing in the voice section
=> Added Twilio API Resources & Fixed Spacing

README.md
Adds resources for CSS Flexbox and CSS Grid from freeCodeCamp.
#57
=> Adds two resources in CSS

README.md
=> add Hanselminutes podcast

README.md
Added resource details for learning Django
=> Added resource for Django

README.md
Add Flutter topic and some learning resources
=> Add Flutter learning resource

README.md
This resource has helped me getting a first glance at javascript back then. I'd love to see it on this list, so others can benefit from it! :)
=> Add Learn X in Y minutes: JavaScript Resource

README.md
Adding Python resources to the list.
=> Added Python Resources

README.md
Adding new resource as part of Women in Tech for Hacktoberfest 2019.
=> add new resource to Women In Tech

README.md
Added two learning resources to react section.
=> Added Resources to React section

README.md
Added awesome Flask tutorial by Miguel Grinberg
=> Add Flask Resource

README.md
Added a really intuitive YouTube tutorial by Traversy Media. Really helpful to get started with git.
=> Added Git and GitHub and Markdown tutorial

README.md
Hi, 
I am Branko from Manning Publications. I thought this book of ours might be a good contribution to the list.
Thanks for your consideration!
=> Added React Hooks in Action

README.md
Added information and links on Android and how to get started for being an android developer. Also shared links to AndroidX and Migrating to this new technology.
Please accept my pull request
#hacktoberfest
=> Added a New topic ANDROID 

README.md
I realized that there were no learning resources for the Ionic framework. So I went ahead and added a few good ones.
=> Added learning resources for Ionic Framework

README.md
Added a new Udacity learning resource for Tensorflow for deep learning.
=> Added a new tensorflow resource

README.md
Added Few Resources For React Native It's An Awesome Library For Creating Android And iOS Apps
So I Decided To Add It Here
=> Added Resources For React Native

README.md
The course contains the first 10 hours of the Complete Flutter Development Bootcamp and will teach you all the fundamentals of Flutter development to get you started. We built this course over months, perfecting the curriculum together with the Flutter team to teach you Flutter from scratch.
=> Add Flutter Course

README.md
Add Mozilla's and JavaScript for cats resources to JavaScript section
=> Other JavaScript resources

README.md
I know it's trivial but might help someone.
=> corrected indexing for Tensorflow icon

README.md
Updated Official Django Tutorials from older v2.1 to the latest supported version 3.0
=> Updated Official Django Tutorials

README.md
Removed broken link for reversing.
is it okay to include the example code that I have created exploring few programming and hacking concepts?
=> Added go,infosec,malware analysis links.

README.md
Hi Gift, I added some more sick picks I believe would be helpful to others
=> Add more sick picks

README.md
Hi Gift, I added some more podcasts I listen to that I believe would be helpful to others :)
=> Add more podcast links

README.md
These resources helped me kick start my journey with Swift and iOS development.
=> create a new topic (swift) and added resources.

README.md
Add a new resource for Typescript and Serverless section.
=> Add a resource for Typescript and Serverless

README.md
I added more resources to Javascript and React section
=> Added more resources to Javascript and React section

README.md
adds a few books and videos. Let me know if there are any resource types that are more useful other than these.
=> adds rails resources.

README.md
Amendment to resources - Added CodeWall to the list of Dev Blogs
=> Amendment to resources

README.md
Added few resources for Kotlin.
Added Kotlin in Table of Contents too.
=> Included Kotlin resources

README.md
Another awesome resource i found.
=> Another awesome resource

README.md
Added Elixir in table of contents and some resources.
=> Included Elixir resources

README.md
Hi
I thought this title might be a great addition to your list of resources.  This course will help new Programmers with creating Live Project on React & Spring Boot with Payment Integration & BarCode Scanner capabilities
Thank you for your consideration
=> feature: Added Create Live Project with React and Spring boot

README.md
Useful for developers who want to turn their side project or
ideas into business
=> adds startups guide for developers

README.md
Added python course which is easy to understand and is amazing for beginners.
=> Added in python

README.md
- Add resources for Git
- Reordering for Alphabetical Order
- Add Twilio section to make href
=> Add git resources and do minor maintenance

README.md
I have added some good resources for learning bash
=> Added Bash resources

README.md
I've added http://vueschool.io/ & https://curated.vuejs.org/ to the list 😀
=> Add Vue Resources

README.md
=> Updating Women in Tech section

README.md
=> added few resources

README.md
writes about open source,
github, gatsby, react, javascript
and is a sharer
#hacktoberfest
=> add dev blog Monica Powell

README.md
checking http vs https connections
#hacktoberfest
=> use https connection on css grid

README.md
Hi 👋 !
Here's 2 complete videos courses for Node.js and JavaScript and a set of interactive tutorials around Node.js.
Seemed like a good fit for your list 🙂
=> Add tutorials for Node.js and JavaScript

README.md
I've added [Joshua Comeau](https://joshwcomeau.com/) in the Developer Blog Section.
=> Add Joshua Comeau

README.md
DevProjects is a community with free real-world projects in multiple coding languages and tech stacks. The website also includes solutions from other developers and discussion board for all users to participate in.
=> Added DevProjects to Angular, Kotlin, Node.js, PHP, Python, React Native, Ruby, Swift, and Vue

README.md
Hi,
Stjepan from Manning here. I thought this latest C# title from our catalog might be a good match for your list. I'm not sure where to add it really, so if you think there is a better placement for it, please, let me know.
Thank you,
=> Added Tiny C# Projects

README.md
Signed-off-by: penghuima <2992426202@qq.com>
Now that serverless computing is popular and is thought to be the future generation of cloud computing, there have been a lot of high caliber papers published recently, and I hope it will provide individuals learning serverless with some rigorous documentation.
=> add serverless papers to Serverless
